name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    - name: 上传打包产物
      uses: actions/upload-artifact@v4
      with:
        name: webpack-build-files # 制品名称，下载的时候会显示这个名字
        path: dist/ # 这里填你Webpack配置里的实际输出目录，如果输出路径不是dist就改这里
        retention-days: 7 # 可选：制品保留天数，默认30天，到期自动删除
    - name: 上传打包文件到服务器
      uses: nogsantos/scp-deploy@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        src: "dist/*"
        # 如果配置了Chroot路径限制，这里填Chroot下的子目录，对应/var/www/your-project/upload
        remote: "/usr/share/nginx/html/fy_api"

